const { block, footerBlock, body } = require("./_helpers");

module.exports = [
  // 1) Abandoned cart
  {
    seedKey: "system/shop-abandoned-cart",
    name: "Abandoned cart",
    category: "E-commerce",
    subject: "You left something behind",
    previewText: "Your cart's still here — finish checking out before it sells out.",
    body: () => body([
      block("heading", { text: "Still thinking it over?", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "We saved your cart so you can pick up right where you left off. Just a heads up — these items are popular and we can't hold them forever.", align: "center", color: "#5A5A5A" }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&auto=format&fit=crop", alt: "Wristwatch on display", width: 600, align: "center", linkHref: "https://example.com/cart" }),
      block("spacer", { height: 24 }),
      block("button", { label: "Return to checkout", href: "https://example.com/cart", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Free shipping on orders over $50 and easy 30-day returns. Questions? Just reply to this email and a real person will help.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 2) Order confirmation
  {
    seedKey: "system/shop-order-confirmation",
    name: "Order confirmation",
    category: "E-commerce",
    subject: "Thanks for your order!",
    previewText: "We've got your order — here's everything you need to know.",
    body: () => body([
      block("heading", { text: "Your order is confirmed", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Thank you for shopping with us! We've received your order and our team is already getting it ready. You'll get another email the moment it ships.", align: "center", color: "#5A5A5A" }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80&auto=format&fit=crop", alt: "Packaged order box ready to ship", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Order #10482", level: 3, align: "left", color: "#1A1A1A" }),
      block("paragraph", { html: "Placed today · Estimated delivery in 3–5 business days · Payment confirmed.", align: "left", color: "#8E8E93" }),
      block("divider", { color: "#E5E5E5", thickness: 1 }),
      block("heading", { text: "What happens next", level: 2, align: "left", color: "#1A1A1A" }),
      block("paragraph", { html: "1. We pack your order with care.  2. You'll receive a shipping confirmation with tracking.  3. Your package arrives at your door — that's it!", align: "left", color: "#5A5A5A" }),
      block("spacer", { height: 24 }),
      block("button", { label: "View your order", href: "https://example.com/orders/10482", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Need to make a change? Reach out within 24 hours and we'll do our best to help before it ships.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 3) Shipping / on its way
  {
    seedKey: "system/shop-shipped",
    name: "Your order is on its way",
    category: "E-commerce",
    subject: "Your order has shipped",
    previewText: "Good news — your package is on the move. Track it here.",
    body: () => body([
      block("heading", { text: "It's on the way!", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Your order just left our warehouse and is heading straight to you. Hang tight — the wait is almost over.", align: "center", color: "#5A5A5A" }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80&auto=format&fit=crop", alt: "Delivery van on the road", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Tracking #1Z999AA10123456784", level: 3, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Estimated arrival: 2–3 business days. We'll let you know if anything changes along the way.", align: "center", color: "#8E8E93" }),
      block("spacer", { height: 24 }),
      block("button", { label: "Track my package", href: "https://example.com/track/10482", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("divider", { color: "#E5E5E5", thickness: 1 }),
      block("paragraph", { html: "Not home for delivery? Most carriers will leave a note or try again the next day. You can also reschedule from the tracking page above.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 4) Back in stock
  {
    seedKey: "system/shop-back-in-stock",
    name: "Back in stock alert",
    category: "E-commerce",
    subject: "It's back — and going fast",
    previewText: "The item you wanted is back in stock. Grab it before it's gone again.",
    body: () => body([
      block("heading", { text: "Good news — it's back!", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "You asked us to let you know, so here we are. The item you had your eye on is back in stock — but it sold out fast last time, so don't wait too long.", align: "center", color: "#5A5A5A" }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80&auto=format&fit=crop", alt: "Red sneakers back in stock", width: 600, align: "center", linkHref: "https://example.com/products/runner" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "The Trail Runner — $128", level: 2, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Limited quantities available. Once they're gone, they're gone for the season.", align: "center", color: "#8E8E93" }),
      block("spacer", { height: 24 }),
      block("button", { label: "Shop now", href: "https://example.com/products/runner", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Heads up: we can't hold items in your cart, so checkout quickly to lock in your pair.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 5) Review / feedback request
  {
    seedKey: "system/shop-review-request",
    name: "Review request",
    category: "E-commerce",
    subject: "How did we do?",
    previewText: "Your order arrived — we'd love to hear what you think.",
    body: () => body([
      block("heading", { text: "How's it working out?", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Your order should have arrived by now, and we hope you love it. Mind sharing a quick review? It takes less than a minute and helps other shoppers (and us) more than you know.", align: "center", color: "#5A5A5A" }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=600&q=80&auto=format&fit=crop", alt: "Customer unboxing a leather bag", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Rate your purchase", level: 3, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "Tap a star, leave a line or two — that's all it takes. Honest feedback, good or bad, is always welcome.", align: "center", color: "#8E8E93" }),
      block("spacer", { height: 24 }),
      block("button", { label: "Write a review", href: "https://example.com/review/10482", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Something not quite right? Reply to this email and we'll make it right — no hassle, no fine print.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 6) New arrivals / product showcase
  {
    seedKey: "system/shop-new-arrivals",
    name: "New arrivals",
    category: "E-commerce",
    subject: "Just in: fresh picks for the season",
    previewText: "New arrivals just dropped — see what we've been working on.",
    body: () => body([
      block("heading", { text: "New arrivals are here", level: 1, align: "center", color: "#1A1A1A" }),
      block("paragraph", { html: "We've been busy. Here are a few new favorites that just landed — handpicked, in limited runs, and ready to ship.", align: "center", color: "#5A5A5A" }),
      block("divider", { color: "#E5E5E5", thickness: 1 }),
      block("image", { src: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80&auto=format&fit=crop", alt: "Canvas weekender bag", width: 600, align: "center", linkHref: "https://example.com/products/weekender" }),
      block("heading", { text: "The Weekender — $94", level: 2, align: "left", color: "#1A1A1A" }),
      block("paragraph", { html: "Waxed canvas, leather trim, and just enough room for two days away. Your new go-to for the spontaneous getaway.", align: "left", color: "#5A5A5A" }),
      block("spacer", { height: 24 }),
      block("image", { src: "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=600&q=80&auto=format&fit=crop", alt: "Minimalist leather wallet", width: 600, align: "center", linkHref: "https://example.com/products/wallet" }),
      block("heading", { text: "The Everyday Wallet — $48", level: 2, align: "left", color: "#1A1A1A" }),
      block("paragraph", { html: "Slim, full-grain leather that only gets better with age. Holds the essentials and slips right into any pocket.", align: "left", color: "#5A5A5A" }),
      block("spacer", { height: 24 }),
      block("image", { src: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80&auto=format&fit=crop", alt: "Stainless steel watch on a band", width: 600, align: "center", linkHref: "https://example.com/products/watch" }),
      block("heading", { text: "The Field Watch — $165", level: 2, align: "left", color: "#1A1A1A" }),
      block("paragraph", { html: "Clean dial, sapphire glass, water resistant to 100m. Built to read at a glance and last for years.", align: "left", color: "#5A5A5A" }),
      block("spacer", { height: 32 }),
      block("button", { label: "Shop the collection", href: "https://example.com/new", bg: "#FF4E4E", fg: "#FFFFFF", align: "center", radius: 10 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Free shipping over $50 · 30-day returns · Members get early access to every drop.", align: "center", color: "#8E8E93" }),
      footerBlock("Drift & Pine Goods · 412 Harbor St, Seattle, WA 98101"),
    ]),
  },
];
