// Events & webinars — system email templates (pack).
const { block, footerBlock, body } = require("./_helpers");
const INK = "#1A1A1A", MUTED = "#5A5A5A", CORAL = "#FF4E4E", WHITE = "#FFFFFF", RULE = "#E5E5E7";

module.exports = [
  {
    seedKey: "system/evt-webinar-invite",
    name: "Webinar invitation",
    category: "Events & webinars",
    subject: "You're invited: {{webinar_title}} — live {{event_date}}",
    previewText: "45 minutes of practical tactics, plus a live Q&A. Seats are free.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/webinar-invite-stage/600/360", alt: "Presenter speaking at a live webinar", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "You're invited to a live webinar", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, join us {{event_date}} at {{event_time}} for {{webinar_title}}. In 45 focused minutes we'll walk through the exact playbook our top customers use — live, with real dashboards on screen.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("button", { label: "Save my seat", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 24 }),
      block("heading", { text: "What you'll walk away with", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "The triggers and timing for each flow, copy you can swipe, and the three metrics that prove a flow is working. Can't make it live? Register anyway and we'll send the recording.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Bring your questions — the final ten minutes are a live Q&A with the host.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-save-the-date",
    name: "Save the date",
    category: "Events & webinars",
    subject: "Save the date: {{event_name}} is coming {{event_date}}",
    previewText: "Mark your calendar now — full details and tickets land soon.",
    body: () => body([
      block("spacer", { height: 16 }),
      block("heading", { text: "Save the date", level: 1, align: "center", color: CORAL }),
      block("heading", { text: "{{event_name}}", level: 2, align: "center", color: INK }),
      block("paragraph", { html: "{{event_date}} · {{event_location}}", align: "center", color: MUTED }),
      block("spacer", { height: 24 }),
      block("image", { src: "https://picsum.photos/seed/save-the-date-calendar/600/360", alt: "Calendar with an event date circled", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("paragraph", { html: "Hi {{first_name}}, something big is on the way and we want you in the room. Block out the day now — registration, the full agenda, and the speaker line-up are just a few weeks away.", align: "center", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Add to calendar", href: "https://example.com", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "We'll be back soon with everything you need to plan your trip. Watch your inbox — early registrants get first pick of sessions.", align: "center", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-registration-confirmed",
    name: "Registration confirmation",
    category: "Events & webinars",
    subject: "You're registered for {{event_name}} 🎉",
    previewText: "Here are your event details, calendar link, and what to expect.",
    body: () => body([
      block("heading", { text: "You're in, {{first_name}}!", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Your registration for {{event_name}} is confirmed. We can't wait to see you there. Here are the details to keep handy.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("divider", { color: RULE, thickness: 2 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Your event details", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Date: {{event_date}}<br>Time: {{event_time}}<br>Where: {{event_location}}<br>Confirmation #: {{registration_id}}", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Add to my calendar", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Before you arrive", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "We'll send a reminder the day before with your join link and a short checklist. If your plans change, you can update or cancel your spot any time from the link in this email.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-starts-in-one-hour",
    name: "Starts in 1 hour reminder",
    category: "Events & webinars",
    subject: "Starts in 1 hour — your join link is inside",
    previewText: "We go live at {{event_time}}. One click and you're in the room.",
    body: () => body([
      block("heading", { text: "We go live in 1 hour", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, {{event_name}} starts today at {{event_time}}. Click below a few minutes early to test your audio and grab a good seat.", align: "center", color: MUTED }),
      block("spacer", { height: 24 }),
      block("button", { label: "Join now", href: "https://example.com", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Quick checklist", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "1. Use a desktop browser for the best view. 2. Keep this link handy — it's unique to you. 3. Have a question ready for the live Q&A.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Running late? No problem — the room stays open, and we'll email you the full recording tomorrow morning.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-speaker-spotlight",
    name: "Speaker spotlight",
    category: "Events & webinars",
    subject: "Meet a speaker: {{speaker_name}} takes the stage at {{event_name}}",
    previewText: "A preview of one session you won't want to miss.",
    body: () => body([
      block("heading", { text: "Speaker spotlight", level: 1, align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://picsum.photos/seed/speaker-spotlight-portrait/600/360", alt: "Portrait of a featured conference speaker", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "{{speaker_name}}, {{speaker_title}}", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, we're thrilled to welcome {{speaker_name}} to the {{event_name}} stage. Their session digs into the strategies that turned a stalled program into a growth engine — with the numbers to back it up.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("heading", { text: "What they'll cover", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "How to prioritize the work that compounds, the metrics worth defending in a budget meeting, and the one habit that separates good teams from great ones. Expect tactics you can apply the same week.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "See the full line-up", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "More spotlights coming soon. Reply and let us know which session you're most excited for.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-agenda-reveal",
    name: "Agenda reveal",
    category: "Events & webinars",
    subject: "The full agenda for {{event_name}} is here",
    previewText: "Two days, dozens of sessions — plan your schedule now.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/agenda-reveal-schedule/600/360", alt: "Event agenda board with session listings", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "The agenda is live", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, the full {{event_name}} schedule just dropped. Here's a taste of what's on the program — build your personal agenda before the best sessions fill up.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Day one", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Opening keynote, the deliverability deep-dive, and a hands-on automation lab where you'll build a working flow with an instructor on hand.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Day two", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Advanced segmentation, reporting that earns budget, and a closing fireside on what's next for the channel — followed by the networking reception.", align: "left", color: INK }),
      block("spacer", { height: 24 }),
      block("button", { label: "Build my schedule", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Sessions are first-come, first-served on the day. Star your favorites now so you don't miss a thing.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-early-bird-tickets",
    name: "Conference early-bird tickets",
    category: "Events & webinars",
    subject: "Early-bird tickets to {{event_name}} end {{deadline_date}}",
    previewText: "Lock in the lowest price before rates go up.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/early-bird-conference/600/360", alt: "Full auditorium at a conference keynote", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Early-bird pricing ends {{deadline_date}}", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "{{event_name}} · {{event_date}} · {{event_location}}", align: "center", color: MUTED }),
      block("paragraph", { html: "Hi {{first_name}}, two days with the people building the fastest-growing programs in the industry. Dozens of sessions, hands-on labs, and the hallway conversations you only get in one room.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Get early-bird tickets", href: "https://example.com", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 2 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Why book now", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "Early-bird passes save you {{discount_amount}} off the standard rate and include the full two days, all labs, and the networking reception. Prices rise the moment the clock runs out.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Bringing the team? Reply for group rates on four or more passes.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-workshop-seats-limited",
    name: "Workshop seats limited",
    category: "Events & webinars",
    subject: "Only {{seats_left}} seats left: {{workshop_title}}",
    previewText: "Small-group, hands-on, and almost full. Claim your spot.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/workshop-hands-on/600/360", alt: "Small group collaborating around laptops in a workshop", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Only {{seats_left}} seats left", level: 1, align: "left", color: CORAL }),
      block("heading", { text: "{{workshop_title}}", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "{{event_date}} · {{event_time}} · Live and capped so everyone gets hands-on help on their own work.", align: "left", color: MUTED }),
      block("paragraph", { html: "Hi {{first_name}}, this isn't a lecture. You'll build something real during the session with an instructor looking over your shoulder. Bring a project you want to ship next week.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Claim my seat", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "You'll leave with", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Finished work you built yourself, the recording to revisit any time, and a checklist to repeat the process on your own afterward.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Seats are first-come, first-served. Once they fill, we open a waitlist for the next cohort.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-virtual-summit",
    name: "Virtual summit invite",
    category: "Events & webinars",
    subject: "{{summit_name}} goes live online {{event_date}} — free to attend",
    previewText: "Join from anywhere. No travel, no ticket, all the sessions.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/virtual-summit-screen/600/360", alt: "Laptop showing a virtual summit live stream", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Our virtual summit is back", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "{{summit_name}} · {{event_date}} · 100% online and free", align: "center", color: MUTED }),
      block("paragraph", { html: "Hi {{first_name}}, join thousands of marketers for a full day of live sessions, panels, and demos — streamed straight to your screen. Watch what you want, when you want, from wherever you are.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Register free", href: "https://example.com", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "On the schedule", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "Keynotes from operators who've scaled real programs, tactical breakout tracks for every level, and live AMAs where you set the questions. Every session is recorded, so registering means you never miss a thing.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("paragraph", { html: "Register once and we'll send your personal link plus reminders before each session you've starred.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },

  {
    seedKey: "system/evt-post-event-recording",
    name: "Post-event recording and thank-you",
    category: "Events & webinars",
    subject: "Thanks for joining — your recording and slides are ready",
    previewText: "Missed a moment? Watch the replay and grab the resources.",
    body: () => body([
      block("heading", { text: "Thanks for joining us", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, thank you for being part of {{event_name}}. As promised, the full recording, the slides, and the resources we mentioned are all ready below.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("image", { src: "https://picsum.photos/seed/post-event-applause/600/360", alt: "Audience applauding at the close of an event", width: 600, align: "center", linkHref: "https://example.com" }),
      block("spacer", { height: 24 }),
      block("button", { label: "Watch the recording", href: "https://example.com", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("spacer", { height: 16 }),
      block("heading", { text: "The resources we mentioned", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "The slide deck, the templates as a ready-to-fork doc, and the dashboard we demoed are all linked from the replay page. Put one idea into practice this week while it's still fresh.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Want the next one?", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Our next session goes live {{next_event_date}}. We'll send an invite soon — keep an eye on your inbox.", align: "left", color: MUTED }),
      footerBlock("Your Company, Inc. · 123 Main St, City, ST 00000"),
    ]),
  },
];
