// Newsletters — system email templates (pack).
const { block, footerBlock, body } = require("./_helpers");
const INK = "#1A1A1A", MUTED = "#5A5A5A", CORAL = "#FF4E4E", WHITE = "#FFFFFF", RULE = "#E5E5E7";

module.exports = [
  // 1. Monthly digest — image-led, three stories with dividers ─────────────────
  {
    seedKey: "system/nlp-monthly-digest-3-stories",
    name: "Monthly digest — 3 stories",
    category: "Newsletters",
    subject: "{{company}} this month: 3 stories worth your time",
    previewText: "The reads, the wins, and what's coming next.",
    body: () => body([
      block("heading", { text: "The {{company}} Monthly", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "Hi {{first_name}}, here's everything that happened this month, distilled into three quick reads.", align: "center", color: MUTED }),
      block("image", { src: "https://picsum.photos/seed/monthlydigest/600/360", alt: "Monthly digest cover", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "1. The big launch", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "We shipped the feature you've been asking about for months. Here's how it works and why it matters for your day-to-day.", align: "left", color: INK }),
      block("button", { label: "Read the story", href: "https://example.com/story-1", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "2. A customer's playbook", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "One team doubled their output without adding headcount. We sat down with them to learn how.", align: "left", color: INK }),
      block("button", { label: "See the playbook", href: "https://example.com/story-2", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "3. What's next", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "A peek at the roadmap for next month. Spoiler: it's our biggest update yet.", align: "left", color: INK }),
      block("button", { label: "Preview the roadmap", href: "https://example.com/story-3", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 32 }),
      footerBlock("The Monthly Co. · 88 Harbor St, Seattle, WA 98101"),
    ]),
  },

  // 2. Weekly roundup — compact, multiple short items ──────────────────────────
  {
    seedKey: "system/nlp-weekly-roundup",
    name: "Weekly roundup — 5 quick hits",
    category: "Newsletters",
    subject: "Your weekly 5: the only updates you missed",
    previewText: "Five things, two minutes, zero fluff.",
    body: () => body([
      block("heading", { text: "This Week in 5", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Morning, {{first_name}}. Grab your coffee — here are the five things worth knowing this week.", align: "left", color: MUTED }),
      block("divider", { color: RULE, thickness: 2 }),
      block("paragraph", { html: "1. The product update everyone's talking about is now live for all plans.", align: "left", color: INK }),
      block("paragraph", { html: "2. We crossed a milestone you helped us reach — more on that next week.", align: "left", color: INK }),
      block("paragraph", { html: "3. A new guide dropped on getting more from your workflows.", align: "left", color: INK }),
      block("paragraph", { html: "4. Office hours move to Thursdays starting this week.", align: "left", color: INK }),
      block("paragraph", { html: "5. One quote we can't stop thinking about, from a reader just like you.", align: "left", color: INK }),
      block("divider", { color: RULE, thickness: 2 }),
      block("button", { label: "Read the full roundup", href: "https://example.com/weekly", bg: CORAL, fg: WHITE, align: "left", radius: 8 }),
      block("spacer", { height: 24 }),
      footerBlock("Roundup Media · 14 Print Row, Austin, TX 78701"),
    ]),
  },

  // 3. Single-story feature — one long-form piece, image hero ───────────────────
  {
    seedKey: "system/nlp-single-story-feature",
    name: "Single-story feature",
    category: "Newsletters",
    subject: "The one story you should read today",
    previewText: "A deeper look at the thing that changed everything.",
    body: () => body([
      block("image", { src: "https://picsum.photos/seed/featurestory/600/360", alt: "Feature story hero", width: 600, align: "center", linkHref: "https://example.com/feature" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Why we rebuilt it from scratch", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "It would have been easier to patch the old system. Instead, we tore it down and started over — and here's the unfiltered story of why.", align: "left", color: INK }),
      block("paragraph", { html: "When the first version shipped three years ago, it solved a real problem. But success has a way of revealing the cracks. As usage grew, the assumptions we baked in early began to fight us.", align: "left", color: INK }),
      block("paragraph", { html: "So we made the call most teams avoid: stop, rethink, rebuild. What follows is the full account — the trade-offs, the late nights, and the moment we knew we'd made the right choice.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Read the full feature", href: "https://example.com/feature", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 32 }),
      footerBlock("Longform Letters · 5 Editorial Way, Brooklyn, NY 11201"),
    ]),
  },

  // 4. Curated links list — text-forward, no image ──────────────────────────────
  {
    seedKey: "system/nlp-curated-links-list",
    name: "Curated links — 6 picks",
    category: "Newsletters",
    subject: "6 links worth your weekend",
    previewText: "Hand-picked reads, watches, and listens from {{company}}.",
    body: () => body([
      block("heading", { text: "The Curated Six", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "No algorithm, no autoplay. Just six things we genuinely enjoyed this week, picked by hand for you.", align: "center", color: MUTED }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Read", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "A sharp essay on doing fewer things, better.\nA reported piece on how small teams ship fast.", align: "left", color: INK }),
      block("heading", { text: "Watch", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "A twelve-minute talk that reframes how you think about focus.\nA short documentary on craft and patience.", align: "left", color: INK }),
      block("heading", { text: "Listen", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "An interview with a founder who quit, came back, and rebuilt.\nA quiet playlist for deep work.", align: "left", color: INK }),
      block("spacer", { height: 24 }),
      block("button", { label: "See all the links", href: "https://example.com/links", bg: CORAL, fg: WHITE, align: "center", radius: 8 }),
      block("spacer", { height: 24 }),
      footerBlock("Curated Inc. · 320 Reading Ln, Portland, OR 97204"),
    ]),
  },

  // 5. Plain-text-style note — minimal, founder voice ───────────────────────────
  {
    seedKey: "system/nlp-plain-text-note",
    name: "Plain-text note from the founder",
    category: "Newsletters",
    subject: "A short note from me to you",
    previewText: "No graphics, no pitch — just a few honest words.",
    body: () => body([
      block("paragraph", { html: "Hi {{first_name}},", align: "left", color: INK }),
      block("paragraph", { html: "I'm writing this one the old-fashioned way — no banners, no buttons fighting for your attention. Just me, typing.", align: "left", color: INK }),
      block("paragraph", { html: "I wanted to say thank you. Building {{company}} has been the hardest and most rewarding thing I've done, and none of it works without people like you choosing to read these notes.", align: "left", color: INK }),
      block("paragraph", { html: "If you ever have feedback — good, bad, or blunt — just reply to this email. It comes straight to me, and I read every one.", align: "left", color: INK }),
      block("paragraph", { html: "More soon.", align: "left", color: INK }),
      block("paragraph", { html: "— The {{company}} team", align: "left", color: MUTED }),
      block("spacer", { height: 32 }),
      footerBlock("Founder's Desk · 7 Quiet St, Madison, WI 53703"),
    ]),
  },

  // 6. Product-update digest — multi-section, what's new / fixed / soon ─────────
  {
    seedKey: "system/nlp-product-update-digest",
    name: "Product update digest",
    category: "Newsletters",
    subject: "What's new in {{company}} this release",
    previewText: "New features, key fixes, and what's coming next.",
    body: () => body([
      block("heading", { text: "Product Update", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "Here's everything that shipped since you last logged in, {{first_name}}.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("heading", { text: "New", level: 2, align: "left", color: CORAL }),
      block("paragraph", { html: "Saved views let you pin the filters you use most.\nA redesigned dashboard loads twice as fast.\nDark mode is finally here.", align: "left", color: INK }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "Improved", level: 2, align: "left", color: CORAL }),
      block("paragraph", { html: "Search now ranks recent items higher.\nExports include the columns you actually care about.", align: "left", color: INK }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "Coming soon", level: 2, align: "left", color: CORAL }),
      block("paragraph", { html: "Team workspaces and granular permissions are in private beta. Want in? Just reply.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "See the full changelog", href: "https://example.com/changelog", bg: CORAL, fg: WHITE, align: "left", radius: 10 }),
      block("spacer", { height: 24 }),
      footerBlock("Product Team · 900 Build Ave, San Jose, CA 95110"),
    ]),
  },

  // 7. Community highlights — member spotlights, image-led ───────────────────────
  {
    seedKey: "system/nlp-community-highlights",
    name: "Community highlights",
    category: "Newsletters",
    subject: "From the {{company}} community this month",
    previewText: "Member wins, fresh threads, and people to follow.",
    body: () => body([
      block("heading", { text: "Community Highlights", level: 1, align: "center", color: INK }),
      block("image", { src: "https://picsum.photos/seed/communityfolks/600/360", alt: "Community members gathered", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "Member of the month", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "This month we're celebrating a member who turned a weekend project into a full-time business — and shared every step in the forum.", align: "left", color: INK }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "Threads worth joining", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "\"What's your morning routine?\" hit 200 replies.\n\"Show your setup\" is back, and the photos are unreal.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Jump into the community", href: "https://example.com/community", bg: CORAL, fg: WHITE, align: "center", radius: 8 }),
      block("spacer", { height: 24 }),
      footerBlock("Community HQ · 42 Gather St, Denver, CO 80202"),
    ]),
  },

  // 8. Best-of recap — year/quarter highlights, numbered ─────────────────────────
  {
    seedKey: "system/nlp-best-of-recap",
    name: "Best of the year — recap",
    category: "Newsletters",
    subject: "The 5 most-loved moments of the year",
    previewText: "A look back at what you read, clicked, and loved most.",
    body: () => body([
      block("heading", { text: "Best of the Year", level: 1, align: "center", color: CORAL }),
      block("paragraph", { html: "Before we turn the page, here's a look back at the moments that resonated most with readers like you, {{first_name}}.", align: "center", color: MUTED }),
      block("spacer", { height: 24 }),
      block("heading", { text: "#5 — The interview series", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Candid conversations that pulled back the curtain on how things really get built.", align: "left", color: INK }),
      block("heading", { text: "#4 — The big how-to", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "The most-saved guide we've ever published.", align: "left", color: INK }),
      block("heading", { text: "#3 — The contrarian take", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "An opinion that split the room — in the best way.", align: "left", color: INK }),
      block("heading", { text: "#2 — The community story", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "A reader's journey that became everyone's favorite read.", align: "left", color: INK }),
      block("heading", { text: "#1 — The one that started it all", level: 3, align: "left", color: INK }),
      block("paragraph", { html: "Our most-shared piece of the year, by a mile.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Revisit the top 5", href: "https://example.com/best-of", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 32 }),
      footerBlock("Recap Press · 11 Annual Ct, Chicago, IL 60601"),
    ]),
  },

  // 9. Expert tips — actionable list, text-only ─────────────────────────────────
  {
    seedKey: "system/nlp-expert-tips",
    name: "Expert tips — 4 actionable ideas",
    category: "Newsletters",
    subject: "4 tips you can use before lunch",
    previewText: "Small changes, real results — from people who've done it.",
    body: () => body([
      block("heading", { text: "4 Tips From the Pros", level: 1, align: "left", color: INK }),
      block("paragraph", { html: "We asked four experts for one thing you can do today. Here's what they said, {{first_name}}.", align: "left", color: MUTED }),
      block("spacer", { height: 16 }),
      block("heading", { text: "Tip 1 — Start with the end", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "Write the headline before the article. If you can't summarize it in one line, it isn't ready.", align: "left", color: INK }),
      block("heading", { text: "Tip 2 — Cut your first draft by half", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "The fastest way to better work is removing the parts that don't earn their place.", align: "left", color: INK }),
      block("heading", { text: "Tip 3 — Ship before you're ready", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "Feedback from the real world beats another week of polishing in private.", align: "left", color: INK }),
      block("heading", { text: "Tip 4 — Review it tomorrow", level: 3, align: "left", color: CORAL }),
      block("paragraph", { html: "A night's sleep is the cheapest editor you'll ever hire.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Get next week's tips", href: "https://example.com/tips", bg: CORAL, fg: WHITE, align: "left", radius: 8 }),
      block("spacer", { height: 24 }),
      footerBlock("Tip Jar Media · 60 Practice Rd, Nashville, TN 37203"),
    ]),
  },

  // 10. Behind-the-scenes — narrative, image-led ────────────────────────────────
  {
    seedKey: "system/nlp-behind-the-scenes",
    name: "Behind the scenes",
    category: "Newsletters",
    subject: "How the sausage actually gets made",
    previewText: "A peek behind the curtain at {{company}}.",
    body: () => body([
      block("heading", { text: "Behind the Scenes", level: 1, align: "center", color: INK }),
      block("paragraph", { html: "Most of what we do never makes the highlight reel. Today, {{first_name}}, we're showing you the messy middle.", align: "center", color: MUTED }),
      block("image", { src: "https://picsum.photos/seed/backstageteam/600/360", alt: "The team at work behind the scenes", width: 600, align: "center", linkHref: "" }),
      block("spacer", { height: 24 }),
      block("heading", { text: "The whiteboard graveyard", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "For every idea we ship, a dozen die on a whiteboard. Here are three we loved but had to let go — and why.", align: "left", color: INK }),
      block("divider", { color: RULE, thickness: 1 }),
      block("heading", { text: "A day in the studio", level: 2, align: "left", color: INK }),
      block("paragraph", { html: "Coffee at eight, chaos by ten, clarity by four. We followed one project from sticky note to shipped.", align: "left", color: INK }),
      block("spacer", { height: 16 }),
      block("button", { label: "Watch the studio tour", href: "https://example.com/behind-the-scenes", bg: CORAL, fg: WHITE, align: "center", radius: 10 }),
      block("spacer", { height: 32 }),
      footerBlock("Studio Notes · 3 Backstage Blvd, Los Angeles, CA 90012"),
    ]),
  },
];
